### ISSUE TITLE
__inline__ and dlsym

### ISSUE THREAD

**Issue by btiffin** [JulNadeauCA/libagar#3]
Hello, Vedge,

Huge fan of libagar.  I'm Brian Tiffin, with the GnuCOBOL project (in Ottawa by the way), and have almost finished up on a user defined function repository binding to a fair number of Agar features and widgets.

I work on a GNU/Linux 64bit machine, and some of the __inline__ modifiers are making the integration a little tricky.  The GnuCOBOL CALL verb relies on dynamic linking via dlsym.  Some functions, AG_Unit2Unit for instance are coming up

    prompt$ cobc -xj units.cob $(agar-config --libs)
    libcob: cannot find module 'AG_Unit2Unit'

Some of the COBOL for this trial

       call "AG_FindUnit" using
           by content "ft" & x"00"
           returning address of agar-feet
       call "AG_FindUnit" using
           by content "m" & x"00"
           returning address of agar-metres

       move pi to metres

       call "AG_Unit2Unit" using
           by value metres
           by reference agar-metres agar-feet
           returning feet

The static __inline__ double declaration is not creating a dlsym findable link symbol.  Where as the FindUnit call works ok, due to the entry in BEGIN_DECLS, sans inline. This issue is many fold worse when trying (salivating for) AG_Web and --enable-web 1.5.1 builds.

To give you a more complete picture, I've documented most of the work behind the current bindings in a thread on SourceForge, https://sourceforge.net/p/open-cobol/discussion/cobol/thread/c2ac66c1/

The objective with the function repository is for developer code in COBOL along the lines of

    move agar-unit2unit(metric-measure, ag-metres, ag-feet) to standard-measure

I've hacked up a compile of 1.5.1 on Ubuntu and Fedora so far, but I'm a bit defeated on finding the symbols that are small t and not big T in nm listings.

One technical point, seemed easy to get round in web.c.  GNU/Linux has no sun_len element in sockaddr_un the and it only seems to be a place holder (perhaps needed when the field is supported), but the code lines end up as sunLen = strlen(sun.sun_path)+1 + sizeof(sun.sun_family); which gcc doesn't choke on.  Alas, I've not gotten to testing much 1.5.1 due to my less than stellar attempts at getting the storage classes correct, complicated by compile time or link time fails.

And now, I'm asking for a little advice.  Do I try and maintain a patch set exposing some of the inline definitions that end up with no entry point?   Or might I ask for more direct assistance in getting clean shared libraries on GNU/Linux and perhaps a more solid binding to Agar from COBOL?  Big Smiley here, maybe the puppy dog eyes if you can see them?

It's a nice toolkit, Vedge.  I'm really looking forward to bragging about GnuCOBOL with Web features.  There is already a demo of AG_Net as COBOL functions in the link above.

If this all works out, and it'll be some work, there will be trials of runtime checks for COBOL screen section (curses based terminal user interface) to Agar based graphical user interface, no change to the COBOL required.  That's a dream, and it will take some work, so, may happen.  Dreams do sometimes come true.

Have good, make well,
Brian

**Comment by JulNadeauCA** [comment]
Hello Brian,

You must accept my apologies for such a late reply. I'm honored to see
your brilliant work on developing COBOL bindings to Agar. Reading
through the Sourceforge thread piqued my curiosity, but I'm completely
new to the language. Any good introduction or books you can suggest?

While working on the new Ada 2012 bindings for Agar 1.6, I've been
running into the exact same problem of inline functions not being dlsym
findable. I had to work around the problem by adding glue functions (in
lowercase) for every inlined function:

	#include <agar/core.h>

	int ag_of_class (void *obj, const char *p) {
		return AG_OfClass(obj, p);
	}

and linked this extra object against my compiled bindings library, with
my Ada spec referring to the lowercase:

	function AG_OfClass
	    (Object  : in Object_not_null_Access;
	     Pattern : in CS.chars_ptr) return C.int
	    with Import, Convention => C, Link_Name => "ag_of_class";

Would it help if I just imported those functions in agar but with
lowercase function names? I was thinking that we could indicate in the
man pages which functions are inline by adding an "inline" keyword to
the function definitions (and further clarify in AG_Intro(3) that the
dlsym findable versions of inline functions are to be found in lowercase
form). It's the solution I can think of where I get to keep my inlines,
and let authors of language bindings share the pain equally :)

Thanks for pointing out the sockaddr_un problem. Since the last release
I have not tested the SVN sources on anything other than FreeBSD yet.
I should be doing that in the next few days. I've been sitting on a
monster diff that I really need to finish and commit (Ada 2012, major
updates to the AG_Surface API, struct cleanups, etc), before I move on
to testing different platforms and release 1.6.0 hopefully in October.

AG_Web was a lot of fun to work on. Part of it evolved from a library we
used in projects at csoft.net including the control panel and webmail.
It was back to the HTML4 days so I'd try to minimize the amount of JS
code. The idea was to have a simple toolkit with things like templates
to make dynamic web programming in C tolerable, since the libraries we
used were mostly C APIs (Berkeley DB, etc). I'm working on a new version
of the libagar.org website which will use AG_Web to make it more dynamic
(allowing users to register and have some kind of a message board to
replace the defunct mailing list).

Looking at examples of COBOL screen sections on google images, I'm so
excited to see Agar being considered as a replacement for something
like this, it could be a really good fit. So many cool user interface
design challenges come to mind.

Please keep me updated!

**Comment by btiffin** [comment]
Thanks for the reply, vedge.

> Any good introduction or books you can suggest?

Yep.  The GnuCOBOL was blessed with a contribution (somewhat out of the blue) in the form of a very comprehensive Programmer's Guide:  https://open-cobol.sourceforge.io/

Along with that, for learning COBOL, Micheal Coughlan at the University of Limerick probably has one of the best tutorials:   http://www.csis.ul.ie/cobol/

And I have a 1600ish page smorgasbord of GnuCOBOL docs at https://open-cobol.sourceforge.io/faq/index.html  (I'll be updating that docset with lots and lots of Agar info once I get cobweb-agar ready for release).

> Would it help if I just imported those functions in agar but with lowercase function names?

Yes indeedy.  Sounds like a sound plan, keep the performance, play nice with the binders.

> AG_Web was a lot of fun to work on.

I'm finding the same.  Really looking forward to advertising GnuCOBOL as web ready.

> So many cool user interface design challenges come to mind.

Yep.   And being more coder-monkey than design-expert, I usually defer to others when it comes to UI.

But I'm starting to lean to small "control panel" designs rather than monolithic GUI screens.  Not to say that multi-widget forms don't have a place, and I'll be doing my best to demonstrate what would be old fashioned green screens in Agar GUI forms (including automatically using Agar fixed pixel widgets from existing COBOL screen section layouts), but that won't be my first choice anymore.  I can't find the entry at the moment, but something akin to Star Trek LCARS one thing at time, slide in, heads up displays.  Why go from 1960 to 1985 when you can jump from 1960 to 2460?  :-)

Along with that, COBOL uses decimal arithmetic, and I might try and squeeze in a new libb (business) to go along with libm and the other usually inaccurate floating point tools we all live with.  COBOL is Computer Business, not so much Computer Science.  Pennies count.  And when you can't accurately store 0.1 without approximating, floating point falls short in most financial use cases.

Will definitely keep you updated, and probably pester you more now (and adding code if that will help). 

One thing I'll need a design help kick on is colours.  We're aiming for a GnuCOBOL colour scheme of Orange/Red, Tech Blue and off-white (what I call recreational beige).  I'm not entirely clear on how to do the RGB steps when it comes to main colours versus the highlights and lowlights and bordering and such in the Agar form of style sheets. I'll know it when I see it, but would not be able to describe it.

Thanks again, looking forwards.

Have good, make well,
Brian

**Comment by JulNadeauCA** [comment]
Hey Brian,

Hopefully the inline and dlsym problems should no longer be an issue with the current sources.

I went over the Core and GUI APIs and made sure that everything that is inlinable is also dlsymmable
(in its lowercase form). I've also added some configure switches to disable inlining entirely or on a per
subsystem basis.

I've also made some API changes so we are now passing AG_Color's and AG_Rect's by reference
instead of by value, hoping that it make things easier for the language bindings (and portability in
general). I had to break the API anyway since AG_Color's size now depends on the compiled Agar
memory model.

The 1.6.0 release is coming along nicely by the way. There are some new contributors and lots of
interesting stuff planned for this summer. Looking forward to continuing our discussion!

Thanks,

**Comment by btiffin** [comment]
I definitely don't log into GitHub often enough.  I'll now apologize for the delayed response on a closed ticket.  I was away from free software volunteering for the better part of a year and still catching up.

1.6.0 trials are working out really well on this Fedora 27 node, 64 bit.  I've been using --disable-threads and --without-inline for the GnuCOBOL binding trials.

I'm still having trouble with --enable-web, the compiles here get tripped up on attributes, but won't complain until you get closer to a 1.6.0 official.   :-)

Other than that, between 1.5.0 and 1.6.0, the only change that had to be made to the early demo COBOL programs was looking for `load-path` in the config.  Easy fix.  Appreciate the new default of $HOME/.progname, makes bootstrapping that much easier.

As part of that, I'm sending a great big Thank You, Julien.  Much more satisfying than previous attempts with cobweb-gtk bindings.  GTK breaks just about every other time you turn around.  Agar does not.  Agar wins.

Looking forward to more discussions too.  You may have heard from Federico from Italy, I've piqued interest in a few of the COBOL programmers that follow along with GnuCOBOL.  Federico is going to be providing a preprocessor for GnuCOBOL with Agar powers.  (He was in the same state of mind as I was regarding GTK and continual breakage being demoralizing).  For Agar one of his quips was "the Agar Gui toolkit is really amazing and strong."  His guicobol INVOKE based preprocessor will be some nice competition for the user defined function based cobweb-agar kit.  Spoil people with choice.

Have good, make well
