### ISSUE TITLE
Compilation of Agar on OpenIndiana failed

### ISSUE THREAD

**Issue by ghost** [JulNadeauCA/libagar#54]
The logs are too long so I use pastebin.

The system has clang 8.0 and by default BSDBuild pick up clang:

Configure: https://pastebin.com/r2kPKmiN
Compilation: https://pastebin.com/QtnxwHRD

When forced to use gcc:

Configure: https://pastebin.com/FzUhNqC9
Compilation: https://pastebin.com/qz5iSGG6 (this log is too long so I can only capture the last part of it).

My guest is the system doesn't support fixed integer data types like int64_t, int16_t,... Please add a workaround to let Agar able to build on this OS. Thanks.

#53 This issue is exactly the same and has not yet resolved. I don't know why he just closed it without any information about if it was resolved or how he fixed it.

**Comment by gh-legacy** [comment]
Update: I tested both int64_t and int16_t with my simple program and it compiled and run without any problems. So the problems lie in your macros magic and BSDBuild configuring. This OS definitely has support for fixed integer data types.

**Comment by JulNadeauCA** [comment]
Can you post the contents of the config.log file generated by configure? It should contain the exact error message emitted from the compiler.

There is also a cosmetic problem with the output due to the echo command missing the "-n" option. If there is an alternative way to print text to the console without a newline, a platform-specific override could be added to the $ECHO_N test in mkconfigure.pl.

I tried to install OpenIndiana on a test machine but the text installer seems to get stuck. I'll try again with the Live DVD version.

**Comment by gh-legacy** [comment]
> I tried to install OpenIndiana on a test machine but the text installer seems to get stuck. I'll try again with the Live DVD version.

Thank you very much for your passionate. The OI installation process is much slower than any Linux distros. You should try the Live DVD or Live USB version, since they contained everything needed for a full desktop. Other installation medias don't have GUI preinstalled.

OI already has everything Agar need so no need to install extra library. You only have to update the system with sudo pkg update -rv first, reboot, then install compiler toolchain with sudo pkg install build-essential, it will install gcc, if you want clang, install it with sudo pkg install clang-80.

**Comment by gh-legacy** [comment]
In case you didn't successfully setup OpenIndiana, here is my VirtualBox image: https://1drv.ms/u/s!Auwd9nlwFHRmakDesevGPpKC1Ac?e=AiVZ8X

**Comment by gh-legacy** [comment]
Hope this issue would be resolved with the next release of Agar alongside with the SDL2 backend. I will keep the VirtualBox image above for a while before removing it, since I'm using the free plan of OneDrive and it's used almost all of my storage space.

**Comment by gh-legacy** [comment]
I deleted the image. Hope you already got it. Please let me know about your progress. Thanks.

**Comment by JulNadeauCA** [comment]
The compilation problems should be resolved as of 1.7.0. The installation guides have also been updated:
https://libagar.org/docs/inst/linux.html

The SDL2 backend is also now available as the "sdl2fb", "sdl2gl" and "sdl2mw" drivers.
